services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: your-strong-static-key
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: your_username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your_password
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-nxfr.onrender.com/
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "n8n"
